#!/usr/bin/env zsh
#
# Powerlevel10k. The instant-prompt preamble lives at the top of rc.zsh, where
# it has to stay.

P10K_THEME="$HOME/dev/resources/powerlevel10k/powerlevel10k.zsh-theme"
if [[ -r "$P10K_THEME" ]]; then
  source "$P10K_THEME"
else
  echo "powerlevel10k missing — run: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/dev/resources/powerlevel10k"
fi

# Generated by `p10k configure`; symlinked from p10k/p10k.zsh
[[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"

# VS Code shell integration. The old config loaded this twice, and the second
# copy ran unguarded, so a shell without `code` on PATH printed an error.
if [[ "$TERM_PROGRAM" == "vscode" ]] && command -v code >/dev/null 2>&1; then
  # RPROMPT confuses VS Code's command detection
  unset RPROMPT RPS1
  source "$(code --locate-shell-integration-path zsh)"
fi
